routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::group(['middleware' => 'auth'], function(){
    // Controllers Within The "App\Http\Controllers\" Namespace
    Route::resource('category', 'CategoryController');
    Route::resource('book', 'BookController');
    Route::get('catalog/autocomplete', 'CategoryController@autocomplete');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Book extends Model
{
    public $fillable = [
        'id',
        'name',
        'author',
        'category_id',
        'published_at',
        'user'
    ];

    public function category()
    {
        return $this->belongsTo('App\Category');
    }

}

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $fillable = [
        'id',
        'name',
        'description'
    ];

    //Consulta para hacer count de los libros
    public function booksCount()
    {
      return $this->hasOne('App\Book')
        ->selectRaw('category_id, count(*) as aggregate')
        ->groupBy('category_id');
    }


    public function getProductsCountAttribute()
    {
      if ( ! array_key_exists('BooksCount', $this->relations))
          $this->load('BooksCount');

      $related = $this->getRelation('BooksCount');

      return ($related) ? (int) $related->aggregate : 0;
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Book;

class BookController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $books = Book::paginate(5);
        return view('books', compact('books'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('book_create')->with('book', '');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'author' => 'required',
            'category_id' => 'required',
            'published_at' => 'required'
        ]);

        $book = new Book($request->all());
        $book->save();

        return redirect()->route('book.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $book = Book::find($id);
        return view('book_create')->with('book', $book);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $this->validate($request, [
          'name' => 'required',
          'author' => 'required',
          'category_id' => 'required',
          'published_at' => 'required'
      ]);

      $book = Book::find($id);
      $bookUpdate = $request->all();
      $book->update($bookUpdate);

      return redirect()->route('book.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $book = Book::find($id);
        $book->delete();

        return response()->json(['status' => true]);
    }

}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use DB;
use App\Category;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(5);
        return view('categories',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category_create')->with('category', '');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
        ]);

        $category = new Category($request->all());
        $category->save();

        return redirect()->route('category.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $records = Category::find($id);
        return view('category_create')->with('category', $records);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'description' => 'required',
        ]);

        $category = Category::find($id);

        // Update company data
        $categoryUpdate = $request->all();
        $category->update($categoryUpdate);

        return redirect()->route('category.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $category = Category::find($id);
        $category->delete();

        return response()->json(['status' => true]);
    }

    public function autocomplete(Request $request){
        if($request->get('term'))
        {
            $term = $request->get('term');

            $results = array();

            $queries = Category::where('name', 'LIKE', '%'.$term.'%')
                                ->take(5)->get();

            foreach ($queries as $query)
            {
                $results[] = [
                    'id' => $query->id,
                    'value' => $query->name
                ];
            }

            return response()->json($results);
        }
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home');
    }
}

resources/views/book_create.blade.php
@extends('layouts.app')

@section('content')

<div class="col-lg-7 col-md-9">
<br>


@if ($book)
    <h1>Editar Libro</h1>
    {!! Form::open(['route' =>  ['book.update', $book->id], 'method' => 'PUT']) !!}
@else
    <h1>Crear Libro</h1>
    {!! Form::open(['route' => 'book.store', 'method' => 'POST']) !!}
@endif

        {{ Form::hidden('category_id', $book ? $book->category_id : null) }}
        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {{ Form::label('name', 'Nombre') }}
            {{ Form::text('name', $book ? $book->name : ''   , ['class' => 'form-control']) }}
            @if ($errors->has('name'))
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('author') ? ' has-error' : '' }}">
            {{ Form::label('author', 'Autor') }}
            {{ Form::text('author', $book ? $book->author : ''   , ['class' => 'form-control']) }}
            @if ($errors->has('author'))
                <span class="help-block">
                    <strong>{{ $errors->first('author') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('category_id') ? ' has-error' : '' }}">
            {{ Form::label('category_name', 'Categoría') }}
            {{ Form::text('category_name', null, array('placeholder' => 'Ingresa el nombre de una categoría','class' => 'form-control','id'=>'category_name')) }}
            <div id="category-help">
                <strong>Es necesario escoger algo</strong>
            </div>
            @if ($errors->has('category_id'))
                <span class="help-block">
                    <strong>{{ $errors->first('category_id') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('published_at') ? ' has-error' : '' }}">
            {{ Form::label('published_at', 'Publicado') }}
            {{ Form::date('published_at', $book ? $book->published_at : \Carbon\Carbon::now()   , ['class' => 'form-control']) }}
            @if ($errors->has('published_at'))
                <span class="help-block">
                    <strong>{{ $errors->first('published_at') }}</strong>
                </span>
            @endif
        </div>

    {{ link_to_route('book.index', 'Cancelar', null, ['class'=>'btn btn-danger']) }}
    {{ Form::submit( $book ? 'Editar' : 'Crear',['class'=>'btn btn-primary']) }}

{!! Form::close() !!}

</div>
@endsection

@push('scripts')

<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

<script>
    $(document).ready( function() {
        $("#category_name").autocomplete({
            source: function(request, response) {
                $.ajax({
                    url: "{{ URL('catalog/autocomplete') }}",
                    data: { term: request.term },
                    success: function (data) {
                        $('#category_id').val('');
                        $('input[type="submit"]').attr('disabled', true);
                        $('#category-help').show();
                        var re = $.ui.autocomplete.escapeRegex(request.term);
                        var matcher = new RegExp( "\W*(" + re + ")\W*", "i" );
                        var transformed = $.map(data, function (item,index) {
                            var t = item.value.replace(matcher,"<span style='font-weight:bold;color:Blue;'>" + re + "</span>");
                            return {
                                value: t,
                                id: item.id,
                                name: item.value
                            };
                        });
                        response(transformed);
                    },
                    error: function () {
                        response([]);
                    }
                });
            },
            minLength: 2,
            select: function(event, ui) {
                $('input[name="category_id"]').val(ui.item.id);
                $('#category_name').val(ui.item.name);

                $('input[type="submit"]').attr('disabled', false);
                $('#category-help').hide();

                return false;
            }
        }).data("ui-autocomplete")._renderItem = function (ul, item) {
            return $("<li></li>")
                .data("item.autocomplete", item)
                .append("<a>" + item.label + "</a>")
                .appendTo(ul);
        };

    });
</script>
@endpush

resources/views/books.blade.php
@extends('layouts.app')

@section('content')

<div class="col-lg-8 col-md-9">
    <div>
    	<h1 style="float: left;">Libros</h1>
    	<a href="{{ route('book.create') }} " class="btn btn-primary" style="width: 20%; float: right;">Agregar libro</a>
    </div>

    <table class="table table-hover">
    	<thead>
    		<tr>
    			<th> Nombre </th>
    			<th> Autor </th>
    			<th> Categoría </th>
                <th> Publicación </th>
                <th> Disponible </th>
                <th> Acciones </th>
    		</tr>
    	</thead>
    	<tbody>
    		@foreach($books as $book)
    		<tr data-href="{{ route('book.edit', $book->id) }}">
    			<td class="clickable-row">{{ $book->name }}</td>
    			<td class="clickable-row" >{{ $book->author }}</td>
                <td class="clickable-row" >{{ $book->Category->name }}</td>
                <td class="clickable-row" >{{ $book->published_at }}</td>
                <td class="" ><button type="button" class="btn btn-success btn-sm open-AddBookDialog" data-toggle="modal" data-taget-id="1"
                data-target="#myModal" data-id="{{ $book->id }}">{{ $book->available ? 'si' : 'no' }}</td>
    			<td>
    				<a href="{{ route('book.edit', $book->id) }}"> <button type="button" class="btn btn-primary">Editar</button> </a>
    				<a href="{{ route('book.destroy', $book->id) }}" class="btn btn-danger delete-element"> Eliminar </a>
    			</td>
    		</tr>
    		@endforeach
    	</tbody>
    </table>
    {{ $books->links() }}
    @include('modal/available');
</div>
@endsection

@push('scripts')
	<script src="{{ asset('js/delete_element.js') }}"></script>
@endpush

resources/views/categories.blade.php
@extends('layouts.app')

@section('content')

<div class="col-lg-8 col-md-9">
    <div>
    	<h1 style="float: left;">Categorías</h1>
    	<a href="{{ route('category.create') }} " class="btn btn-primary" style="width: 20%; float: right;">Crear categoría</a>
    </div>

    <table class="table table-hover">
      	<thead>
        		<tr>
          			<th> Nombre </th>
          			<th> Descripción </th>
          			<th> Libros </th>
                <th> Acciones </th>
        		</tr>
      	</thead>

      	<tbody>
        		@foreach($categories as $category)
        		<tr data-href="{{ route('category.edit', $category->id) }}">
          			<td class="clickable-row">{{ $category->name }}</td>
          			<td class="clickable-row" >{{ $category->description }}</td>
                <td>{{ $category->productsCount }}</td>
          			<td>
          				<a href="{{ route('category.edit', $category->id) }}"> <button type="button" class="btn btn-primary">Editar</button> </a>
          				<a href="{{ route('category.destroy', $category->id) }}" class="btn btn-danger delete-element"> Eliminar </a>
          			</td>
        		</tr>
        		@endforeach
      	</tbody>

    </table>
    {{ $categories->links() }}
</div>
@endsection

@push('scripts')
	<script src="{{ asset('js/delete_element.js') }}"></script>
@endpush

resources/views/category_create.blade.php
@extends('layouts.app')

@section('content')

<div class="col-lg-7 col-md-9">

@if ($category)
    <h1>Crear Categoría</h1>
    {!! Form::open(['route' =>  ['category.update', $category->id], 'method' => 'PUT']) !!}
@else
    <h1>Crear Categoría</h1>
    {!! Form::open(['route' => 'category.store', 'method' => 'POST']) !!}
@endif

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
            {{ Form::label('name', 'Nombre') }}
            {{ Form::text('name', $category ? $category->name : ''   , ['class' => 'form-control'])}}
            @if ($errors->has('name'))
                <span class="help-block">
                    <strong>{{ $errors->first('name') }}</strong>
                </span>
            @endif
        </div>

        <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
            {{ Form::label('description', 'Descrición') }}
            {{ Form::text('description', $category ? $category->description : ''   , ['class' => 'form-control'])}}
            @if ($errors->has('description'))
                <span class="help-block">
                    <strong>{{ $errors->first('description') }}</strong>
                </span>
            @endif
        </div>

    {{ link_to_route('category.index', 'Cancelar', null, ['class'=>'btn btn-danger']) }}
    {{ Form::submit( $category ? 'Editar' : 'Crear',['class'=>'btn btn-primary']) }}

{!! Form::close() !!}

</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
                <div class="navbar-header">

                    <!-- Collapsed Hamburger -->
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                        <span class="sr-only">Toggle Navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

                    <!-- Branding Image -->
                    <a class="navbar-brand" href="{{ url('/') }}">
                        {{ config('app.name', 'Laravel') }}
                    </a>
                </div>

                <div class="collapse navbar-collapse" id="app-navbar-collapse">
                    <!-- Left Side Of Navbar -->
                    <ul class="nav navbar-nav">
                        &nbsp;
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="nav navbar-nav navbar-right">
                        <!-- Authentication Links -->
                        @if (Auth::guest())
                            <li><a href="{{ route('login') }}">Login</a></li>
                            <li><a href="{{ route('register') }}">Register</a></li>
                        @else
                            <li class="dropdown">
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        @endif
                    </ul>
                </div>
            </div>
        </nav>

        @if (Auth::user())
            @include('menu')
        @endif

        @yield('content')
    </div>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>
    <script src="{{ asset('js/common.js') }}"></script>

    @yield('js')
    @stack('scripts')
</body>
</html>

resources/views/menu.blade.php
<div class="col-md-3" style="min-height: 100%;">
  <div class="wrapper" style="display: flex; width: 100%; align-items: stretch;">
    <nav id="sidebar">
          <div class="sidebar-header">
              <h3>Library Sidebar</h3>
          </div>

          <ul class="list-unstyled components">
              <p>Menu</p>
              <li class="active">
                  <a href="{{ route('book.index') }} " aria-expanded="false" class="dropdown-toggle">Libros</a>
              </li>
              <li class="active">
                  <a href="{{ route('category.index') }} " aria-expanded="false" class="dropdown-toggle">Categorías</a>
              </li>
          </ul>
      </nav>

  </div>

</div>

resources/views/modal/available.blade.php
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                <h4 class="modal-title" id="myModalLabel">Disponibilidad</h4>
            </div>
            <div class="modal-body">
                <label>¿El libro está disponible?</label>
                <div class="form-group">
                <fieldset id="available">
                    <input type="hidden" name="bookAvailable" id="bookAvailable" value="">
                    <div>
                        {{ Form::radio('available', '1', true) }}
                        <label for="available">Si</label>
                    </div>
                    <div>
                        {{ Form::radio('available', '0') }}
                        <label for="available">No</label>
                    </div>
                </fieldset>
                </div>
            </div>
            <div class="modal-footer">
                <a href="#" data-dismiss="modal" class="btn btn-danger"> Cancelar </a>
                <a href="#" data-dismiss="modal" class="btn btn-primary"> Actualizar </a>
            </div>
        </div>
    </div>
</div>